export const myProjects = [
  {
    title: "GPT-4",
    cat: "react",
    imgPath: "./8.png",
    link: "https://degitl.web.app/",
    git: "https://github.com/Abdullah02020/GPT-4",
    sup: "Harness GPT-4's power for enhanced development. Dive into the future of AI-driven creation.",
  },
  {
    title: "Hoobank - The Future of Banking",
    cat: "react",
    imgPath: "./10.png",
    link: "https://hoobanky.web.app/",
    git: "https://github.com/Abdullah02020/project_hoobank-main",
    sup: "Elevating finance with sleek design and next-gen tech.",
  },

  {
    title: "The Web-3 Communication ",
    cat: "react",
    imgPath: "./11.png",
    link: "https://status-web3.web.app/",
    git: "https://github.com/Abdullah02020/web-3",
    sup: "Harness the power of decentralization with Status,",
  },

  {
    title: "Brew & Bean - Coffee Shop",
    cat: "react",
    imgPath: "./2.png",
    sup: "The virtual cafe experience, brewed with React.",
  },
  {
    title: "Pawfect Supplies - Pet Essentials",
    cat: "react",
    imgPath: "./3.png",
    sup: "React-powered shopping for your furry friends.",
  },
  {
    title: "Worksquare",
    cat: "css",
    imgPath: "./4.png",
    link: "https://abdullah02020.github.io/Worksquare/",
    git: "https://github.com/Abdullah02020/Worksquare",
    sup: "LET’S FIND THE RIGHT WORKSPACE FOR YOU AND YOUR TEAM",
  },
  {
    title: "Workforce - Temp Workers Solutions",
    cat: "css",
    imgPath: "./5.png",
    link: "https://abdullah02020.github.io/work-force/",
    git: "https://github.com/Abdullah02020/work-force",
    sup: "Empowering businesses with flexible staffing solutions.",
  },
  {
    title: "QuickEat - Gourmet Meals on Demand",
    cat: "css",
    imgPath: "./6.png",
    link: "https://abdullah02020.github.io/Quickeat/",
    git: "https://github.com/Abdullah02020/Quickeat",
    sup: "Savor the speed of flavor.elivered directly to your door.",
  },
  {
    title: "DIGITAL - Design & Creativity Agency",
    cat: "css",
    imgPath: "./12.png",
    link: "https://abdullah02020.github.io/Digtel/",
    git: "https://github.com/Abdullah02020/Digtel",
    sup: "Where creativity meets cutting-edge design.",
  },
  {
    title: "The Wellhall - Resort & Spa Hotel",
    cat: "css",
    imgPath: "./7.png",
    link: "https://abdullah02020.github.io/The-Wellhall/",
    git: "https://github.com/Abdullah02020/The-Wellhall",
    sup: "Your sanctuary of relaxation and luxury.",
  },

  {
    title: "Kaffen - London's Finest Coffee House",
    cat: "css",
    imgPath: "./9.png",
    link: "https://abdullah02020.github.io/Kaffen/",
    git: "https://github.com/Abdullah02020/Kaffen",
    sup: "Savor the essence of London in every cup.",
  },

  {
    title: "EDUFORD-UNIVERSITY - Education ",
    cat: "css",
    imgPath: "./14.png",
    link: "https://abdullah02020.github.io/EDUFORD-UNIVERSITY/",
    git: "https://github.com/Abdullah02020/EDUFORD-UNIVERSITY",
    sup: "Shaping the future with world-class education.",
  },
  {
    title: "Leon - Creative Agency Web Template",
    cat: "css",
    imgPath: "./13.png",
    link: "https://abdullah02020.github.io/leon/",
    git: "https://github.com/Abdullah02020/leon",
    sup: "Crafting elegance in simplicity for the modern web.",
  },
  {
    title: "CREATIVE AGENCY - Web Innovation Hub",
    cat: "css",
    imgPath: "./16.png",
    link: "https://abdullah02020.github.io/CREATIVE-AGENCY/",
    git: "https://github.com/Abdullah02020/CREATIVE-AGENCY",
    sup: "Where vision meets web brilliance. Elevate your online presence.",
  },
  {
    title: "Kasper - Artistic Expression Redefined",
    cat: "css",
    imgPath: "./15.png",
    link: "https://abdullah02020.github.io/Kasper-website/",
    git: "https://github.com/Abdullah02020/Kasper-website",
    sup: "Where art meets digital elegance. Explore the canvas of tomorrow.",
  },
];
