export const myProjects = [
  {
    title: "جي بي تي-4",
    cat: "react",
    imgPath: "./8.png",
    link: "https://degitl.web.app/",
    git: "https://github.com/Abdullah02020/GPT-4",
    sup: "استغل قوة جي بي تي-4 لتطوير متقدم. اغمر نفسك في مستقبل الإبداع بدعم الذكاء الاصطناعي.",
  },
  {
    title: "هوبانك - مستقبل البنوك",
    cat: "react",
    imgPath: "./10.png",
    link: "https://hoobanky.web.app/",
    git: "https://github.com/Abdullah02020/project_hoobank-main",
    sup: "نرتقي بالمالية بتصميم أنيق وتقنية الجيل القادم.",
  },
  {
    title: "الثورة في التواصل ويب-3",
    cat: "react",
    imgPath: "./11.png",
    link: "https://status-web3.web.app/",
    git: "https://github.com/Abdullah02020/web-3",
    sup: "استلهم المستقبل بقوة الويب-3، حيث تتحد التكنولوجيا  بأساليب التواصل .",
  },
  {
    title: "متجر نايكي",
    cat: "react",
    imgPath: "./17.png",
    link: "https://nike-stor.web.app/",
    git: "https://github.com/Abdullah02020/Nike",
    sup: "ادخل عالم نايكي. استكشف أحدث ما في عالم الأزياء والابتكار الرياضي.",
  },
  {
    title: "برو وبين - مقهى",
    cat: "react",
    imgPath: "./2.png",
    sup: "قيد الإنجاز، قريبًا تجربة فريدة تنتظركم.",
  },
  {
    title: "بافكت سبلايز - لوازم الحيوانات الأليفة",
    cat: "react",
    imgPath: "./3.png",
    sup: "قيد التطوير، استعد لتجربة تسوق استثنائية لصديقك الفروي.",
  },
  {
    title: "وركسكوير",
    cat: "css",
    imgPath: "./4.png",
    link: "https://abdullah02020.github.io/Worksquare/",
    git: "https://github.com/Abdullah02020/Worksquare",
    sup: "دعونا نجد المساحة العملية المثالية لك ولفريقك",
  },
  {
    title: "وركفورس - حلول العمال المؤقتين",
    cat: "css",
    imgPath: "./5.png",
    link: "https://abdullah02020.github.io/work-force/",
    git: "https://github.com/Abdullah02020/work-force",
    sup: "تمكين الأعمال بحلول توظيف مرنة.",
  },
  {
    title: "كويك إيت - وجبات جورميه عند الطلب",
    cat: "css",
    imgPath: "./6.png",
    link: "https://abdullah02020.github.io/Quickeat/",
    git: "https://github.com/Abdullah02020/Quickeat",
    sup: "استمتع بسرعة النكهة. مباشرة إلى باب منزلك.",
  },
  {
    title: "ديجيتال - وكالة التصميم والإبداع",
    cat: "css",
    imgPath: "./12.png",
    link: "https://abdullah02020.github.io/Digtel/",
    git: "https://github.com/Abdullah02020/Digtel",
    sup: "عندما تصبح التقنية فنًا، والأفكار تتحول إلى واقع ملموس.",
  },
  {
    title: "ويلهال - فندق المنتجع والسبا",
    cat: "css",
    imgPath: "./7.png",
    link: "https://abdullah02020.github.io/The-Wellhall/",
    git: "https://github.com/Abdullah02020/The-Wellhall",
    sup: "ملاذك من الاسترخاء والفخامة.",
  },
  {
    title: "كافين - أفضل مقهى في لندن",
    cat: "css",
    imgPath: "./9.png",
    link: "https://abdullah02020.github.io/Kaffen/",
    git: "https://github.com/Abdullah02020/Kaffen",
    sup: "أين تلتقي نكهات القهوة الفاخرة بأسرار لندن العريقة.",
  },
  {
    title: "إيدوفورد-يونيفيرسيتي - التعليم",
    cat: "css",
    imgPath: "./14.png",
    link: "https://abdullah02020.github.io/EDUFORD-UNIVERSITY/",
    git: "https://github.com/Abdullah02020/EDUFORD-UNIVERSITY",
    sup: "نشكل المستقبل بتعليم عالمي المستوى.",
  },
  {
    title: "ليون - قالب ويب للوكالات الإبداعية",
    cat: "css",
    imgPath: "./13.png",
    link: "https://abdullah02020.github.io/leon/",
    git: "https://github.com/Abdullah02020/leon",
    sup: "نحت الأناقة في البساطة للويب الحديث.",
  },
  {
    title: "وكالة الإبداع - مركز الابتكار الويبي",
    cat: "css",
    imgPath: "./16.png",
    link: "https://abdullah02020.github.io/CREATIVE-AGENCY/",
    git: "https://github.com/Abdullah02020/CREATIVE-AGENCY",
    sup: "حيث تلتقي الرؤية ببراعة الويب. ارتقِ بحضورك على الإنترنت.",
  },
  {
    title: "كاسبر - إعادة تعريف التعبير الفني",
    cat: "css",
    imgPath: "./15.png",
    link: "https://abdullah02020.github.io/Kasper-website/",
    git: "https://github.com/Abdullah02020/Kasper-website",
    sup: "حيث يلتقي الفن بالأناقة الرقمية. استكشف لوحة الغد.",
  },
];
